extends: gpt_small.yaml

trainer:
  # Recommended to set max_steps to a value that makes (context length * batch size * max_steps) approximately 327,680,000
  max_steps: 80000
  save_interval: 1000
  log_interval: 20
  val_interval: 100
